name: group_exito
description: "Test application for Group Exito, a platform for managing and sharing events."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dio: ^5.2.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.1.0
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  go_router: ^16.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_flavorizr: ^2.4.1
  flutter_gen: ^5.10.0
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/concert-plaza-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_gen:
  output: lib/core/resources/gen/

  integrations:
    image: true
    flutter_svg: true
  colors:
    enabled: true
    outputs:
      class_name: ColorToken
    inputs:
      - assets/color/colors.xml

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    dev:
      app:
        name: "Group Exito Dev"
      android:
        applicationId: "com.group.exito.dev"
      ios:
        bundleId: "com.group.exito.dev"
    prod:
      app:
        name: "Group Exito"
      android:
        applicationId: "com.group.exito"
      ios:
        bundleId: "com.group.exito"

flutter:
  generate: true
  default-flavor: dev
  uses-material-design: false

  assets:
    - assets/images/
    - assets/svgs/
    - assets/color/
    - assets/envs/

  fonts:
    - family: Lato-Black
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
    - family: Lato-Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Lato-Light
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: Lato-Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Lato-Thin
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
